# Nord theme for Alacritty - TOML format

[colors.primary]
foreground = "#d8dee9"
background = "#2e3440"
dim_foreground = "#4c566a"
bright_foreground = "#eceff4"

[colors.cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.vi_mode_cursor]
text = "#2e3440"
cursor = "#d8dee9"

[colors.search.matches]
foreground = "#2e3440"
background = "#88c0d0"

[colors.search.focused_match]
foreground = "#2e3440"
background = "#81a1c1"

[colors.hints.start]
foreground = "#2e3440"
background = "#ebcb8b"

[colors.hints.end]
foreground = "#2e3440"
background = "#a3be8c"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#d8dee9"
background = "#3b4252"

[colors.selection]
text = "#2e3440"
background = "#d8dee9"

[colors.normal]
black =   "#3b4252"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#88c0d0"
white =   "#e5e9f0"

[colors.bright]
black =   "#4c566a"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#8fbcbb"
white =   "#eceff4"

[colors.dim]
black =   "#3b4252"
red =     "#bf616a"
green =   "#a3be8c"
yellow =  "#ebcb8b"
blue =    "#81a1c1"
magenta = "#b48ead"
cyan =    "#88c0d0"
white =   "#e5e9f0"
